name: Windows

on:
  push:
  pull_request:
  schedule:
  #Every Sunday at midnight
  - cron:  '0 0 * * 0'

jobs:
  test:
    name: "Test"
    strategy:
      matrix:
        version_test: ["NoVersion","3.1"]
    runs-on: windows-latest
    steps:
    
      - name: Setup Python
        uses: actions/setup-python@v2
        
      - name: Checkout
        uses: actions/checkout@v2.3.4
      
      - name: Cache tools
        uses: actions/cache@v2
        with:
          path: tools
          key: ${{ runner.os }}-cmakes
          
      - name: "Download cmake packages"
        run: |
            python -m venv venv
            .\venv\Scripts\pip.exe install -r .\requirements.txt
            .\venv\Scripts\python.exe cmake_downloader.py --latest_patch
            .\venv\Scripts\python.exe cmake_min_version.py --full_search FULL_SEARCH $GITHUB_WORKSPACE\tests\${{ matrix.version_test }}\
